import { describe, expect, it } from "vitest";

import { buildUrlWithQueries } from "./build-url";

describe("buildUrlWithQueries", () => {
	it("appends query parameters when buildQueryString returns content", () => {
		const result = buildUrlWithQueries("/api/runs", {
			page: 2,
			sort: "created_desc",
		});

		expect(result).toBe("/api/runs?page=2&sort=created_desc");
	});

	it("returns the original url when queries serialize to an empty query string", () => {
		const result = buildUrlWithQueries("/api/runs", {
			ignoreNull: null,
			ignoreUndefined: undefined,
		});

		expect(result).toBe("/api/runs");
	});

	it("returns the original url when params are empty", () => {
		const result = buildUrlWithQueries("/api/runs", {});

		expect(result).toBe("/api/runs");
	});

	it("keeps current concatenation behavior for urls that already contain query params", () => {
		const result = buildUrlWithQueries("/api/runs?existing=1", {
			page: 2,
		});

		expect(result).toBe("/api/runs?existing=1?page=2");
	});

	it("keeps current concatenation behavior for urls that contain a hash fragment", () => {
		const result = buildUrlWithQueries("/api/runs#section", {
			page: 2,
		});

		expect(result).toBe("/api/runs#section?page=2");
	});

	it("preserves encoded query content generated by buildQueryString", () => {
		const result = buildUrlWithQueries("/api/runs", {
			text: "a b&c=d?",
			emoji: "hello🙂",
		});

		expect(result).toBe("/api/runs?text=a+b%26c%3Dd%3F&emoji=hello%F0%9F%99%82");
	});

	it("keeps current concatenation behavior for urls ending with '?'", () => {
		const result = buildUrlWithQueries("/api/runs?", {
			page: 2,
		});

		expect(result).toBe("/api/runs??page=2");
	});

	it("keeps current concatenation behavior for urls ending with '&'", () => {
		const result = buildUrlWithQueries("/api/runs?existing=1&", {
			page: 2,
		});

		expect(result).toBe("/api/runs?existing=1&?page=2");
	});

	it("handles an empty base url", () => {
		const result = buildUrlWithQueries("", {
			page: 2,
		});

		expect(result).toBe("?page=2");
	});

	it("returns deterministic output for same input", () => {
		const url = "/api/runs";
		const params = { page: 2, sort: "created_desc" };

		expect(buildUrlWithQueries(url, params)).toBe(buildUrlWithQueries(url, params));
	});
});
