/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PrivateAppRouteRouteImport } from './routes/_private/_app/route'
import { Route as publicMeshRouteRouteImport } from './routes/(public)/_mesh/route'
import { Route as PrivateDevicesVerifyRouteImport } from './routes/_private/devices/verify'
import { Route as PrivateAppFlowsRouteImport } from './routes/_private/_app/flows'
import { Route as publicMeshLoginRouteImport } from './routes/(public)/_mesh/login'
import { Route as publicMeshActivateServerRouteImport } from './routes/(public)/_mesh/activate-server'

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAppRouteRoute = PrivateAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const publicMeshRouteRoute = publicMeshRouteRouteImport.update({
  id: '/(public)/_mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateDevicesVerifyRoute = PrivateDevicesVerifyRouteImport.update({
  id: '/devices/verify',
  path: '/devices/verify',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAppFlowsRoute = PrivateAppFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => PrivateAppRouteRoute,
} as any)
const publicMeshLoginRoute = publicMeshLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicMeshRouteRoute,
} as any)
const publicMeshActivateServerRoute =
  publicMeshActivateServerRouteImport.update({
    id: '/activate-server',
    path: '/activate-server',
    getParentRoute: () => publicMeshRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/activate-server': typeof publicMeshActivateServerRoute
  '/login': typeof publicMeshLoginRoute
  '/flows': typeof PrivateAppFlowsRoute
  '/devices/verify': typeof PrivateDevicesVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute
  '/activate-server': typeof publicMeshActivateServerRoute
  '/login': typeof publicMeshLoginRoute
  '/flows': typeof PrivateAppFlowsRoute
  '/devices/verify': typeof PrivateDevicesVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/(public)/_mesh': typeof publicMeshRouteRouteWithChildren
  '/_private/_app': typeof PrivateAppRouteRouteWithChildren
  '/_private/': typeof PrivateIndexRoute
  '/(public)/_mesh/activate-server': typeof publicMeshActivateServerRoute
  '/(public)/_mesh/login': typeof publicMeshLoginRoute
  '/_private/_app/flows': typeof PrivateAppFlowsRoute
  '/_private/devices/verify': typeof PrivateDevicesVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activate-server' | '/login' | '/flows' | '/devices/verify'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activate-server' | '/login' | '/flows' | '/devices/verify'
  id:
    | '__root__'
    | '/_private'
    | '/(public)/_mesh'
    | '/_private/_app'
    | '/_private/'
    | '/(public)/_mesh/activate-server'
    | '/(public)/_mesh/login'
    | '/_private/_app/flows'
    | '/_private/devices/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  publicMeshRouteRoute: typeof publicMeshRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/_app': {
      id: '/_private/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateAppRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/(public)/_mesh': {
      id: '/(public)/_mesh'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicMeshRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/devices/verify': {
      id: '/_private/devices/verify'
      path: '/devices/verify'
      fullPath: '/devices/verify'
      preLoaderRoute: typeof PrivateDevicesVerifyRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/_app/flows': {
      id: '/_private/_app/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof PrivateAppFlowsRouteImport
      parentRoute: typeof PrivateAppRouteRoute
    }
    '/(public)/_mesh/login': {
      id: '/(public)/_mesh/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicMeshLoginRouteImport
      parentRoute: typeof publicMeshRouteRoute
    }
    '/(public)/_mesh/activate-server': {
      id: '/(public)/_mesh/activate-server'
      path: '/activate-server'
      fullPath: '/activate-server'
      preLoaderRoute: typeof publicMeshActivateServerRouteImport
      parentRoute: typeof publicMeshRouteRoute
    }
  }
}

interface PrivateAppRouteRouteChildren {
  PrivateAppFlowsRoute: typeof PrivateAppFlowsRoute
}

const PrivateAppRouteRouteChildren: PrivateAppRouteRouteChildren = {
  PrivateAppFlowsRoute: PrivateAppFlowsRoute,
}

const PrivateAppRouteRouteWithChildren = PrivateAppRouteRoute._addFileChildren(
  PrivateAppRouteRouteChildren,
)

interface PrivateRouteRouteChildren {
  PrivateAppRouteRoute: typeof PrivateAppRouteRouteWithChildren
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateDevicesVerifyRoute: typeof PrivateDevicesVerifyRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateAppRouteRoute: PrivateAppRouteRouteWithChildren,
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateDevicesVerifyRoute: PrivateDevicesVerifyRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface publicMeshRouteRouteChildren {
  publicMeshActivateServerRoute: typeof publicMeshActivateServerRoute
  publicMeshLoginRoute: typeof publicMeshLoginRoute
}

const publicMeshRouteRouteChildren: publicMeshRouteRouteChildren = {
  publicMeshActivateServerRoute: publicMeshActivateServerRoute,
  publicMeshLoginRoute: publicMeshLoginRoute,
}

const publicMeshRouteRouteWithChildren = publicMeshRouteRoute._addFileChildren(
  publicMeshRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  publicMeshRouteRoute: publicMeshRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
