/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as publicMeshRouteImport } from './routes/(public)/_mesh'
import { Route as PrivateDevicesVerifyRouteImport } from './routes/_private/devices/verify'
import { Route as publicMeshLoginRouteImport } from './routes/(public)/_mesh/login'
import { Route as publicMeshActivateServerRouteImport } from './routes/(public)/_mesh/activate-server'

const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any)
const publicMeshRoute = publicMeshRouteImport.update({
  id: '/(public)/_mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateDevicesVerifyRoute = PrivateDevicesVerifyRouteImport.update({
  id: '/devices/verify',
  path: '/devices/verify',
  getParentRoute: () => PrivateRoute,
} as any)
const publicMeshLoginRoute = publicMeshLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicMeshRoute,
} as any)
const publicMeshActivateServerRoute =
  publicMeshActivateServerRouteImport.update({
    id: '/activate-server',
    path: '/activate-server',
    getParentRoute: () => publicMeshRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/activate-server': typeof publicMeshActivateServerRoute
  '/login': typeof publicMeshLoginRoute
  '/devices/verify': typeof PrivateDevicesVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute
  '/activate-server': typeof publicMeshActivateServerRoute
  '/login': typeof publicMeshLoginRoute
  '/devices/verify': typeof PrivateDevicesVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/(public)/_mesh': typeof publicMeshRouteWithChildren
  '/_private/': typeof PrivateIndexRoute
  '/(public)/_mesh/activate-server': typeof publicMeshActivateServerRoute
  '/(public)/_mesh/login': typeof publicMeshLoginRoute
  '/_private/devices/verify': typeof PrivateDevicesVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activate-server' | '/login' | '/devices/verify'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activate-server' | '/login' | '/devices/verify'
  id:
    | '__root__'
    | '/_private'
    | '/(public)/_mesh'
    | '/_private/'
    | '/(public)/_mesh/activate-server'
    | '/(public)/_mesh/login'
    | '/_private/devices/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  publicMeshRoute: typeof publicMeshRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/(public)/_mesh': {
      id: '/(public)/_mesh'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicMeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/devices/verify': {
      id: '/_private/devices/verify'
      path: '/devices/verify'
      fullPath: '/devices/verify'
      preLoaderRoute: typeof PrivateDevicesVerifyRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/(public)/_mesh/login': {
      id: '/(public)/_mesh/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicMeshLoginRouteImport
      parentRoute: typeof publicMeshRoute
    }
    '/(public)/_mesh/activate-server': {
      id: '/(public)/_mesh/activate-server'
      path: '/activate-server'
      fullPath: '/activate-server'
      preLoaderRoute: typeof publicMeshActivateServerRouteImport
      parentRoute: typeof publicMeshRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateDevicesVerifyRoute: typeof PrivateDevicesVerifyRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateDevicesVerifyRoute: PrivateDevicesVerifyRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface publicMeshRouteChildren {
  publicMeshActivateServerRoute: typeof publicMeshActivateServerRoute
  publicMeshLoginRoute: typeof publicMeshLoginRoute
}

const publicMeshRouteChildren: publicMeshRouteChildren = {
  publicMeshActivateServerRoute: publicMeshActivateServerRoute,
  publicMeshLoginRoute: publicMeshLoginRoute,
}

const publicMeshRouteWithChildren = publicMeshRoute._addFileChildren(
  publicMeshRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  publicMeshRoute: publicMeshRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
