/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PrivateNavbarRouteRouteImport } from './routes/_private/_navbar/route'
import { Route as publicMeshRouteRouteImport } from './routes/(public)/_mesh/route'
import { Route as PrivateDevicesVerifyRouteImport } from './routes/_private/devices/verify'
import { Route as publicMeshLoginRouteImport } from './routes/(public)/_mesh/login'
import { Route as publicMeshActivateServerRouteImport } from './routes/(public)/_mesh/activate-server'
import { Route as PrivateNavbarFlowsRouteRouteImport } from './routes/_private/_navbar/flows/route'
import { Route as PrivateNavbarFlowsIndexRouteImport } from './routes/_private/_navbar/flows/index'

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateNavbarRouteRoute = PrivateNavbarRouteRouteImport.update({
  id: '/_navbar',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const publicMeshRouteRoute = publicMeshRouteRouteImport.update({
  id: '/(public)/_mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateDevicesVerifyRoute = PrivateDevicesVerifyRouteImport.update({
  id: '/devices/verify',
  path: '/devices/verify',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const publicMeshLoginRoute = publicMeshLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicMeshRouteRoute,
} as any)
const publicMeshActivateServerRoute =
  publicMeshActivateServerRouteImport.update({
    id: '/activate-server',
    path: '/activate-server',
    getParentRoute: () => publicMeshRouteRoute,
  } as any)
const PrivateNavbarFlowsRouteRoute = PrivateNavbarFlowsRouteRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => PrivateNavbarRouteRoute,
} as any)
const PrivateNavbarFlowsIndexRoute = PrivateNavbarFlowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateNavbarFlowsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/flows': typeof PrivateNavbarFlowsRouteRouteWithChildren
  '/activate-server': typeof publicMeshActivateServerRoute
  '/login': typeof publicMeshLoginRoute
  '/devices/verify': typeof PrivateDevicesVerifyRoute
  '/flows/': typeof PrivateNavbarFlowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute
  '/activate-server': typeof publicMeshActivateServerRoute
  '/login': typeof publicMeshLoginRoute
  '/devices/verify': typeof PrivateDevicesVerifyRoute
  '/flows': typeof PrivateNavbarFlowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/(public)/_mesh': typeof publicMeshRouteRouteWithChildren
  '/_private/_navbar': typeof PrivateNavbarRouteRouteWithChildren
  '/_private/': typeof PrivateIndexRoute
  '/_private/_navbar/flows': typeof PrivateNavbarFlowsRouteRouteWithChildren
  '/(public)/_mesh/activate-server': typeof publicMeshActivateServerRoute
  '/(public)/_mesh/login': typeof publicMeshLoginRoute
  '/_private/devices/verify': typeof PrivateDevicesVerifyRoute
  '/_private/_navbar/flows/': typeof PrivateNavbarFlowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flows'
    | '/activate-server'
    | '/login'
    | '/devices/verify'
    | '/flows/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activate-server' | '/login' | '/devices/verify' | '/flows'
  id:
    | '__root__'
    | '/_private'
    | '/(public)/_mesh'
    | '/_private/_navbar'
    | '/_private/'
    | '/_private/_navbar/flows'
    | '/(public)/_mesh/activate-server'
    | '/(public)/_mesh/login'
    | '/_private/devices/verify'
    | '/_private/_navbar/flows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  publicMeshRouteRoute: typeof publicMeshRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/_navbar': {
      id: '/_private/_navbar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateNavbarRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/(public)/_mesh': {
      id: '/(public)/_mesh'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicMeshRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/devices/verify': {
      id: '/_private/devices/verify'
      path: '/devices/verify'
      fullPath: '/devices/verify'
      preLoaderRoute: typeof PrivateDevicesVerifyRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/(public)/_mesh/login': {
      id: '/(public)/_mesh/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicMeshLoginRouteImport
      parentRoute: typeof publicMeshRouteRoute
    }
    '/(public)/_mesh/activate-server': {
      id: '/(public)/_mesh/activate-server'
      path: '/activate-server'
      fullPath: '/activate-server'
      preLoaderRoute: typeof publicMeshActivateServerRouteImport
      parentRoute: typeof publicMeshRouteRoute
    }
    '/_private/_navbar/flows': {
      id: '/_private/_navbar/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof PrivateNavbarFlowsRouteRouteImport
      parentRoute: typeof PrivateNavbarRouteRoute
    }
    '/_private/_navbar/flows/': {
      id: '/_private/_navbar/flows/'
      path: '/'
      fullPath: '/flows/'
      preLoaderRoute: typeof PrivateNavbarFlowsIndexRouteImport
      parentRoute: typeof PrivateNavbarFlowsRouteRoute
    }
  }
}

interface PrivateNavbarFlowsRouteRouteChildren {
  PrivateNavbarFlowsIndexRoute: typeof PrivateNavbarFlowsIndexRoute
}

const PrivateNavbarFlowsRouteRouteChildren: PrivateNavbarFlowsRouteRouteChildren =
  {
    PrivateNavbarFlowsIndexRoute: PrivateNavbarFlowsIndexRoute,
  }

const PrivateNavbarFlowsRouteRouteWithChildren =
  PrivateNavbarFlowsRouteRoute._addFileChildren(
    PrivateNavbarFlowsRouteRouteChildren,
  )

interface PrivateNavbarRouteRouteChildren {
  PrivateNavbarFlowsRouteRoute: typeof PrivateNavbarFlowsRouteRouteWithChildren
}

const PrivateNavbarRouteRouteChildren: PrivateNavbarRouteRouteChildren = {
  PrivateNavbarFlowsRouteRoute: PrivateNavbarFlowsRouteRouteWithChildren,
}

const PrivateNavbarRouteRouteWithChildren =
  PrivateNavbarRouteRoute._addFileChildren(PrivateNavbarRouteRouteChildren)

interface PrivateRouteRouteChildren {
  PrivateNavbarRouteRoute: typeof PrivateNavbarRouteRouteWithChildren
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateDevicesVerifyRoute: typeof PrivateDevicesVerifyRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateNavbarRouteRoute: PrivateNavbarRouteRouteWithChildren,
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateDevicesVerifyRoute: PrivateDevicesVerifyRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface publicMeshRouteRouteChildren {
  publicMeshActivateServerRoute: typeof publicMeshActivateServerRoute
  publicMeshLoginRoute: typeof publicMeshLoginRoute
}

const publicMeshRouteRouteChildren: publicMeshRouteRouteChildren = {
  publicMeshActivateServerRoute: publicMeshActivateServerRoute,
  publicMeshLoginRoute: publicMeshLoginRoute,
}

const publicMeshRouteRouteWithChildren = publicMeshRouteRoute._addFileChildren(
  publicMeshRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  publicMeshRouteRoute: publicMeshRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
